# vim: set filetype=yaml sw=2:
sudo: required
dist: trusty
before_install:
  - sudo locale-gen
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update -y -qq
  - sudo apt-get install -y python3-all python3-all-dev build-essential python3-setuptools python3-wheel python3-docutils python3-sphinx python3-flake8 python3.1-complete python3.2-complete python3.3-complete python3.5-complete python3.6 wget python-pip python3-pip python3.7 python3.7-dev python3.7-distutils
  - sudo pip3 install wheel

install: true
script: make test TESTARGS=
